apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-demo
  description: An example deployment of a Backstage application.
spec:
  type: website
  owner: guests
  lifecycle: experimental
